### ISSUE TITLE
Add support for all data sets available through frenchdata

### ISSUE THREAD

**Issue by voigtstefan** [tidy-finance/r-tidyfinance#30]
Currently, a curated tribble in `list_supported_types_ff` limits the datasets one can retrieve via the `frenchdata` backend. This seems unnecessarily restrictive. I propose to lift this restriction.

1. Extend the `list_supported_types_ff` to contain *all* datasets which can be retrieved (see `frenchdata::get_french_data_list()`). Obtaining useful `type` descriptions requires some tweaking of the dataset names. 
2. Extend the `download_data_factors_ff` function to provide an option to pass on the output for non-industry and non-3 or 5-factor models. 

In the long run, we probably want to have a pipeline that usefully maps dataset names to types. At this stage, I honestly do not see the advantage of the defaults in the type column.

**Comment by voigtstefan** [comment]
Implemented two changes:
1. I expanded the list "list_supported_types_ff" to contain all existing dataset_names from frenchdata. Only challenge is to align with the pre-existing curated list (which is also partially used in vignettes, so I did not want to change the names). 
2. I allowed dataset_names which I label as "raw" (= not parted of the curated list) to be returned as is without column renaming, such as we already do for industry portfolios.

**Comment by christophscheuch** [comment]
@voigtstefan I don't want to release it as it is in the PR because it feels very "beta", in particular the "raw" attribute makes little conceptual sense to me in light of the rest. If people start to use it like this, it will be very hard to improve the types without breaking changes and then we have some annoying legacy code to carry around. 

I'll investigate how we can process the data sets so that we don't need any "raw" tags and make a proposal asap.

**Comment by voigtstefan** [comment]
Totally get that, my commit was intended to show a way out. Check out the sample code I provided, it seems natural to start from the dataset names provided in frenchdata. If we have a common naming convention (e.g. "factors_ff_#portfolios_additional-info_frequency") I'd be happy to build it. The only legacy issue to consider is then the current legacy tribble.

**Comment by voigtstefan** [comment]
A fast alternative would be to add a second check which does apply if the type is not in provided files but instead coincides with the name of a frenchdata dataset. That way, there would be a way to retrieve extra data without specific documentation as workaround. However, I'd prefer a stable solution

**Comment by christophscheuch** [comment]
What I'd prefer:
- Download all data sets from ff to extract all possible column names (script is running at the moment)
- Kick out data sets that cannot be downloaded using frenchdata (I'll provide a complete list when the script is done, I don't understand the problem yet, e.g. "100 Portfolios Formed on Size and Operating Profitability (10 x 10) [ex. Dividends]")
- Provide explicit column renaming logic in the processing code  based on the possible column names(e.g. mkt_excess = mkt-rf)
- Rename all the ff data types using regex as you suggested and replace the old types (makes more sense tbh to do this data-driven)
- Don't use the raw labels at all
- Update blog post and vignette and docus

Downloading all possible column names takes longer than expected because so many things don't work, so please be patient.

**Comment by christophscheuch** [comment]
> A fast alternative would be to add a second check which does apply if the type is not in provided files but instead coincides with the name of a frenchdata dataset. That way, there would be a way to retrieve extra data without specific documentation as workaround. However, I'd prefer a stable solution

I think going forward it is feasible and sensible to provide the FF data type names for lookup in supported types. Maybe we can include it in the PR, but let's focus on the cleaning part and making data sets work first.
