### ISSUE TITLE
Align date columns across data sets

### ISSUE THREAD

**Issue by christophscheuch** [tidy-finance/r-tidyfinance#42]
We want to have the following:
- `date` column which refers to the beginning of period of each row in a table in Date format (YYYY-MM-DD). For instance, in "wrds_crsp_monthly" the date column refers to the beginning of a month, while in "wrds_compustat_annual" the date refers to beginning of a year. These date columns are then correctly parsed and **ready to be used for joins** or **date manipulations** (e.g. adding or subtracting months and years). 
- `reference_date` column which refers to the date to which the row refers to. For instance, for "crsp_monthly" this is the last date of a month reported price and for "wrds_compustat_annual" it is the date that refers to the date reported in the filing (="datadate"). Runner up: `recorded_date` maybe better because it is less appealing to be used for joins?
- A clear documentation for each dataset how `date` and `referecence_date` are parsed. 

Should we rather use `date_reference`? `reference_date` nudges users more to use `date` because of autocomplete. 

We don't like
- `datadate` because it does not say anthing about its meaning
- `publication_date` is not true for all instances (e.g. "crsp_monthly")
- `original_date`  
- `source_date` would indicate the data provider but also carries not much meaning
- `recorded_date` 
- `date_information` 
- any more ideas?

**Comment by patrick-weiss** [comment]
For CRSP `date` makes sense (and follows our current definition, right?). However, I think the definition is not useful for Compustat. Consider a company that has a fiscal year that is not the calendar year. Neither the current nor the last year is *correct*, so what then? Moreover, from an accounting perspective, I think it makes sense that `date` is the reporting date (e.g., balance sheet items are as of a period's end; slightly trickier with cash flows and income statement items). However, I think that `date` would be useless if it varies at the day level (except for daily data, of course).

Consequently, we could define `date`: The first day of the reporting month for non-daily data (i.e., "YYYY-MM-01") and the actual day for higher-frequency data (i.e., "YYYY-MM-DD"). However, this reads very cumbersome.

Alternatively, we do not include a `date` for Compustat and similar data with frequencies lower than monthly. Including such a confusing `date` would otherwise lead to poor useability. From my perspective, it should be as easy as possible to merge CRSP and Compustat given a common variable in both datasets.

**Comment by patrick-weiss** [comment]
I think `reference_date` >> `reported_date` as there are reporting dates (or announcement dates) that have a different interpretation.
