### ISSUE TITLE
pkgdown website

### ISSUE THREAD

**Issue by m-muecke** [tidy-finance/r-tidyfinance#50]
A package website with pkgdown would be perhaps nice. The only thing what would've to be done is to either add the credentials for WRDS as a secret for the GitHub Action to access or use `@examplesIf` or alternatives to check for the credenticals and only then run it. This should also solve the error of the inital r-cmd-check action that I've added, i.e. running examples and vignettes.

On that note how have you solved that issue with CRAN, I thought they run the examples and vignettes in their checks.

**Comment by christophscheuch** [comment]
Ad pkgdown website: I don't support this idea because it would compete with tidy-finance.org. We rather should think about how to integrate the tidyfinance package in the book at some ppint. 

Ad WRDS secrets: unfortunately, WRDS requires 2FA and caches auth by IP address and device for 30 days. This makes it imho close to impossible to integrate with Github Actions or CRAN. I'm cheating in the vignettes because WRDS code is simply not executed.

**Comment by m-muecke** [comment]
Makes sense and there is always the r-universe site: https://tidy-finance.r-universe.dev/tidyfinance
